infopage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('places.urls')),
    path('admin/', admin.site.urls),
]

places/urls.py
from django.urls import path

from places import views

app_name = 'places'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail', views.detail, name='detail'),
    path('<int:place_id>/detail', views.detail, name='detail'),
    path('<int:place_id>/delete/', views.delete, name='delete'),
    path('upsert', views.upsert, name='upsert'),
]

places/models.py
from django.db import models


class Places(models.Model):
    name = models.CharField(max_length=255)
    address_state = models.CharField(max_length=255) #estado
    address_city = models.CharField(max_length=255,null=True, blank=True) #cidade
    address_neighborhood = models.CharField(max_length=255,null=True, blank=True) # bairro
    address_complement = models.TextField(null=True, blank=True) # bairro
    create_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.name

places/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Places
from django.utils import timezone


def index(request, important_message=None):
    place_list = Places.objects.order_by('-create_date')
    context = {'place_list': place_list}
    return render(request, 'places/index.html', context)


def detail(request, place_id=''):
    place_selected = {"id": ''}
    if(place_id != ''):
        place_selected = Places.objects.get(id=place_id)

    return render(request, 'places/detail.html', {'place': place_selected})


def delete(request, place_id):
    try:
        place2Delete = Places.objects.get(pk=place_id)
        place2Delete.delete()
        return render(request, 'places/delete.html', {
            'place': place2Delete,
            'important_message': "Your place has been deleted successfully",
        })
    except (KeyError, Places.DoesNotExist):
        return render(request, 'places/delete.html', {
            'place': place2Delete,
            'important_message': "could not delete your place.",
        })


def upsert(request):
    _id = request.POST['id']
    _name = request.POST['name']

    if(_id == ''):
        try:
            newPlace = Places(name=_name, create_date=timezone.now())
            newPlace.save()
            return render(request, 'places/detail.html', {
                'place': newPlace,
                'important_message': "Your place has been saved",
            })
        except (KeyError, Places.DoesNotExist):
            return render(request, 'places/detail.html', {
                'place': newPlace,
                'important_message': "could not save your new place.",
            })

    else:
        try:
            place2Update = Places.objects.get(pk=_id)
            place2Update.name = _name
            place2Update.save()
            return render(request, 'places/detail.html', {
                'place': place2Update,
                'important_message': "Your place has been updated successfully",
            })
        except (KeyError, Places.DoesNotExist):
            return render(request, 'places/detail.html', {
                'place': newPlace,
                'important_message': "could not update your new place.",
            })

places/templates/places/delete.html
<h1>{{ place.name }}</h1>

{% if important_message %}
<p><strong>{{ important_message }}</strong></p>
{% endif %}

<p hidden="true" name="id" id="id" value="{{ place.id }}" />
<p name="name" id="name" value="{{ place.name }}" />

places/templates/places/detail.html
<h1>{{ place.name }}</h1>

{% if important_message %}
<p><strong>{{ important_message }}</strong></p>
{% endif %}

<form action="{% url 'places:upsert' %}" method="post">
    {% csrf_token %}
    <input type="text" hidden=true name="id" id="id" value="{{ place.id }}" />
    <input type="text" name="name" id="name" value="{{ place.name }}" />
    <input type="submit" value="salvar" />
</form>

places/templates/places/index.html
{% if important_message %}
<p><strong>{{ important_message }}</strong></p>
{% endif %}

{% if place_list %}
<ul>
    {% for place in place_list %}
    <li><a href="{% url 'places:detail' place.id %}">{{ place.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No places are available.</p>
{% endif %}